export interface MLBTeamMeta {
  id: number;
  name: string;
  shortName: string;
  jpName: string;
  abbreviation: string;
  logo: string;
  primaryColor: string;
  secondaryColor: string;
  league: 'AL' | 'NL';
  division: 'East' | 'Central' | 'West';
}

export const MLB_TEAMS: Record<number, MLBTeamMeta> = {
  // National League West
  119: {
    id: 119,
    name: 'Los Angeles Dodgers',
    shortName: 'Dodgers',
    jpName: 'ドジャース',
    abbreviation: 'LAD',
    logo: 'https://www.mlbstatic.com/team-logos/119.svg',
    primaryColor: '#005A9C',
    secondaryColor: '#EF3E42',
    league: 'NL',
    division: 'West',
  },
  135: {
    id: 135,
    name: 'San Diego Padres',
    shortName: 'Padres',
    jpName: 'パドレス',
    abbreviation: 'SD',
    logo: 'https://www.mlbstatic.com/team-logos/135.svg',
    primaryColor: '#2F241D',
    secondaryColor: '#FFC425',
    league: 'NL',
    division: 'West',
  },
  137: {
    id: 137,
    name: 'San Francisco Giants',
    shortName: 'Giants',
    jpName: 'ジャイアンツ',
    abbreviation: 'SF',
    logo: 'https://www.mlbstatic.com/team-logos/137.svg',
    primaryColor: '#FD5A1E',
    secondaryColor: '#27251F',
    league: 'NL',
    division: 'West',
  },
  109: {
    id: 109,
    name: 'Arizona Diamondbacks',
    shortName: 'D-backs',
    jpName: 'ダイヤモンドバックス',
    abbreviation: 'AZ',
    logo: 'https://www.mlbstatic.com/team-logos/109.svg',
    primaryColor: '#A71930',
    secondaryColor: '#E3D4AD',
    league: 'NL',
    division: 'West',
  },
  115: {
    id: 115,
    name: 'Colorado Rockies',
    shortName: 'Rockies',
    jpName: 'ロッキーズ',
    abbreviation: 'COL',
    logo: 'https://www.mlbstatic.com/team-logos/115.svg',
    primaryColor: '#33006F',
    secondaryColor: '#C4CED4',
    league: 'NL',
    division: 'West',
  },

  // National League East
  121: {
    id: 121,
    name: 'New York Mets',
    shortName: 'Mets',
    jpName: 'メッツ',
    abbreviation: 'NYM',
    logo: 'https://www.mlbstatic.com/team-logos/121.svg',
    primaryColor: '#002D72',
    secondaryColor: '#FF5910',
    league: 'NL',
    division: 'East',
  },
  143: {
    id: 143,
    name: 'Philadelphia Phillies',
    shortName: 'Phillies',
    jpName: 'フィリーズ',
    abbreviation: 'PHI',
    logo: 'https://www.mlbstatic.com/team-logos/143.svg',
    primaryColor: '#E81828',
    secondaryColor: '#002D72',
    league: 'NL',
    division: 'East',
  },
  144: {
    id: 144,
    name: 'Atlanta Braves',
    shortName: 'Braves',
    jpName: 'ブレーブス',
    abbreviation: 'ATL',
    logo: 'https://www.mlbstatic.com/team-logos/144.svg',
    primaryColor: '#CE1141',
    secondaryColor: '#13274F',
    league: 'NL',
    division: 'East',
  },
  146: {
    id: 146,
    name: 'Miami Marlins',
    shortName: 'Marlins',
    jpName: 'マーリンズ',
    abbreviation: 'MIA',
    logo: 'https://www.mlbstatic.com/team-logos/146.svg',
    primaryColor: '#00A3E0',
    secondaryColor: '#EF3340',
    league: 'NL',
    division: 'East',
  },
  120: {
    id: 120,
    name: 'Washington Nationals',
    shortName: 'Nationals',
    jpName: 'ナショナルズ',
    abbreviation: 'WSH',
    logo: 'https://www.mlbstatic.com/team-logos/120.svg',
    primaryColor: '#AB0003',
    secondaryColor: '#14225A',
    league: 'NL',
    division: 'East',
  },

  // National League Central
  112: {
    id: 112,
    name: 'Chicago Cubs',
    shortName: 'Cubs',
    jpName: 'カブス',
    abbreviation: 'CHC',
    logo: 'https://www.mlbstatic.com/team-logos/112.svg',
    primaryColor: '#0E3386',
    secondaryColor: '#CC3433',
    league: 'NL',
    division: 'Central',
  },
  158: {
    id: 158,
    name: 'Milwaukee Brewers',
    shortName: 'Brewers',
    jpName: 'ブリュワーズ',
    abbreviation: 'MIL',
    logo: 'https://www.mlbstatic.com/team-logos/158.svg',
    primaryColor: '#12284B',
    secondaryColor: '#FFC52F',
    league: 'NL',
    division: 'Central',
  },
  138: {
    id: 138,
    name: 'St. Louis Cardinals',
    shortName: 'Cardinals',
    jpName: 'カージナルス',
    abbreviation: 'STL',
    logo: 'https://www.mlbstatic.com/team-logos/138.svg',
    primaryColor: '#C41E3A',
    secondaryColor: '#0C2340',
    league: 'NL',
    division: 'Central',
  },
  134: {
    id: 134,
    name: 'Pittsburgh Pirates',
    shortName: 'Pirates',
    jpName: 'パイレーツ',
    abbreviation: 'PIT',
    logo: 'https://www.mlbstatic.com/team-logos/134.svg',
    primaryColor: '#FDB827',
    secondaryColor: '#000000',
    league: 'NL',
    division: 'Central',
  },
  113: {
    id: 113,
    name: 'Cincinnati Reds',
    shortName: 'Reds',
    jpName: 'レッズ',
    abbreviation: 'CIN',
    logo: 'https://www.mlbstatic.com/team-logos/113.svg',
    primaryColor: '#C6011F',
    secondaryColor: '#000000',
    league: 'NL',
    division: 'Central',
  },

  // American League East
  147: {
    id: 147,
    name: 'New York Yankees',
    shortName: 'Yankees',
    jpName: 'ヤンキース',
    abbreviation: 'NYY',
    logo: 'https://www.mlbstatic.com/team-logos/147.svg',
    primaryColor: '#003087',
    secondaryColor: '#E4002C',
    league: 'AL',
    division: 'East',
  },
  111: {
    id: 111,
    name: 'Boston Red Sox',
    shortName: 'Red Sox',
    jpName: 'レッドソックス',
    abbreviation: 'BOS',
    logo: 'https://www.mlbstatic.com/team-logos/111.svg',
    primaryColor: '#BD3039',
    secondaryColor: '#0C2340',
    league: 'AL',
    division: 'East',
  },
  110: {
    id: 110,
    name: 'Baltimore Orioles',
    shortName: 'Orioles',
    jpName: 'オリオールズ',
    abbreviation: 'BAL',
    logo: 'https://www.mlbstatic.com/team-logos/110.svg',
    primaryColor: '#DF4601',
    secondaryColor: '#000000',
    league: 'AL',
    division: 'East',
  },
  139: {
    id: 139,
    name: 'Tampa Bay Rays',
    shortName: 'Rays',
    jpName: 'レイズ',
    abbreviation: 'TB',
    logo: 'https://www.mlbstatic.com/team-logos/139.svg',
    primaryColor: '#092C5C',
    secondaryColor: '#8FBCE6',
    league: 'AL',
    division: 'East',
  },
  141: {
    id: 141,
    name: 'Toronto Blue Jays',
    shortName: 'Blue Jays',
    jpName: 'ブルージェイズ',
    abbreviation: 'TOR',
    logo: 'https://www.mlbstatic.com/team-logos/141.svg',
    primaryColor: '#134A8E',
    secondaryColor: '#E8291C',
    league: 'AL',
    division: 'East',
  },

  // American League West
  117: {
    id: 117,
    name: 'Houston Astros',
    shortName: 'Astros',
    jpName: 'アストロズ',
    abbreviation: 'HOU',
    logo: 'https://www.mlbstatic.com/team-logos/117.svg',
    primaryColor: '#EB6E1F',
    secondaryColor: '#002D62',
    league: 'AL',
    division: 'West',
  },
  140: {
    id: 140,
    name: 'Texas Rangers',
    shortName: 'Rangers',
    jpName: 'レンジャーズ',
    abbreviation: 'TEX',
    logo: 'https://www.mlbstatic.com/team-logos/140.svg',
    primaryColor: '#003278',
    secondaryColor: '#C0111F',
    league: 'AL',
    division: 'West',
  },
  136: {
    id: 136,
    name: 'Seattle Mariners',
    shortName: 'Mariners',
    jpName: 'マリナーズ',
    abbreviation: 'SEA',
    logo: 'https://www.mlbstatic.com/team-logos/136.svg',
    primaryColor: '#0C2C56',
    secondaryColor: '#005C5C',
    league: 'AL',
    division: 'West',
  },
  108: {
    id: 108,
    name: 'Los Angeles Angels',
    shortName: 'Angels',
    jpName: 'エンゼルス',
    abbreviation: 'LAA',
    logo: 'https://www.mlbstatic.com/team-logos/108.svg',
    primaryColor: '#BA0021',
    secondaryColor: '#003263',
    league: 'AL',
    division: 'West',
  },
  133: {
    id: 133,
    name: 'Oakland Athletics',
    shortName: 'Athletics',
    jpName: 'アスレチックス',
    abbreviation: 'OAK',
    logo: 'https://www.mlbstatic.com/team-logos/133.svg',
    primaryColor: '#003831',
    secondaryColor: '#EFB21E',
    league: 'AL',
    division: 'West',
  },

  // American League Central
  114: {
    id: 114,
    name: 'Cleveland Guardians',
    shortName: 'Guardians',
    jpName: 'ガーディアンズ',
    abbreviation: 'CLE',
    logo: 'https://www.mlbstatic.com/team-logos/114.svg',
    primaryColor: '#0C2340',
    secondaryColor: '#E31937',
    league: 'AL',
    division: 'Central',
  },
  118: {
    id: 118,
    name: 'Kansas City Royals',
    shortName: 'Royals',
    jpName: 'ロイヤルズ',
    abbreviation: 'KC',
    logo: 'https://www.mlbstatic.com/team-logos/118.svg',
    primaryColor: '#004687',
    secondaryColor: '#BD9B60',
    league: 'AL',
    division: 'Central',
  },
  116: {
    id: 116,
    name: 'Detroit Tigers',
    shortName: 'Tigers',
    jpName: 'タイガース',
    abbreviation: 'DET',
    logo: 'https://www.mlbstatic.com/team-logos/116.svg',
    primaryColor: '#0C2340',
    secondaryColor: '#FA4616',
    league: 'AL',
    division: 'Central',
  },
  142: {
    id: 142,
    name: 'Minnesota Twins',
    shortName: 'Twins',
    jpName: 'ツインズ',
    abbreviation: 'MIN',
    logo: 'https://www.mlbstatic.com/team-logos/142.svg',
    primaryColor: '#002B5C',
    secondaryColor: '#D31145',
    league: 'AL',
    division: 'Central',
  },
  145: {
    id: 145,
    name: 'Chicago White Sox',
    shortName: 'White Sox',
    jpName: 'ホワイトソックス',
    abbreviation: 'CWS',
    logo: 'https://www.mlbstatic.com/team-logos/145.svg',
    primaryColor: '#27251F',
    secondaryColor: '#C4CED4',
    league: 'AL',
    division: 'Central',
  },
};

export const DEFAULT_FAVORITE_TEAM_ID = 119; // Los Angeles Dodgers

export function getTeamMeta(teamId: number, fallbackName?: string): MLBTeamMeta {
  if (MLB_TEAMS[teamId]) {
    return MLB_TEAMS[teamId];
  }
  return {
    id: teamId,
    name: fallbackName || `Team #${teamId}`,
    shortName: fallbackName || `Team`,
    jpName: fallbackName || `チーム`,
    abbreviation: fallbackName ? fallbackName.substring(0, 3).toUpperCase() : 'MLB',
    logo: `https://www.mlbstatic.com/team-logos/${teamId}.svg`,
    primaryColor: '#1d4ed8',
    secondaryColor: '#60a5fa',
    league: 'NL',
    division: 'West',
  };
}

export const ALL_TEAMS_LIST = Object.values(MLB_TEAMS).sort((a, b) => a.jpName.localeCompare(b.jpName, 'ja'));
